---

- include_tasks: 01-CreacionVolumenes.yaml
- include_tasks: 02-CreacionFileSystem.yaml
- include_tasks: 03-InstalarPaquetes.yaml
- include_tasks: 04-ConfigurarAcceso.yaml
- include_tasks: 05-Firewall.yaml
