---

- name: Tareas Comunes 
  hosts: all
  become: true  
  gather_facts: false

  tasks:
    - name: Instalamos kubernetes
      command: dnf install -y kubelet kubeadm kubectl --disableexcludes=kubernetes
    - name: Activamos kubernetes
      command: systemctl enable kubelet
    - name: Iniciamos kubernetes
      command: systemctl start kubelet   
    - name: Configuramos kubeadm
      command: kubeadm config images pull
      
      
      
